const featuresData = [
  {
    id: 1,
    icon: '/images/icon/Boiling.png',
    title: 'Boiling ',
    size: '2.3GB',
    downloads: 15234,
    category: 'Pool boiling',
    description: 'Data on flow boiling behaviors under different conditions.',
  },
  {
    id: 2,
    icon: '/images/icon/BubbleID.png',
    title: 'Bubble ID ',
    size: '1.8GB',
    downloads: 12345,
    category: 'Heat Transfer',
    description: 'Images and data for identifying and tracking bubbles in liquids.',
  },
  {
    id: 3,
    icon: '/images/icon/condensation.jpeg',
    title: 'Condensation',
    size: '3.5GB',
    downloads: 9876,
    category: 'Acoustic',
    description: 'Acoustic emission and thermofluidic data of steady-state flow condensation tests',
  },
  // {
  //   id: 4,
  //   icon: "/images/icon/material.jpeg",
  //   title: "Material",
  //   size: "4.0GB",
  //   downloads: 54321,
  //   category: "Materials Science",
  //   description: "Properties of metals, polymers, and composites.",
  // },
  // {
  //   id: 5,
  //   icon: "/images/icon/thermal.jpeg",
  //   title: "Thermal",
  //   size: "5.0GB",
  //   downloads: 25000,
  //   category: "Lorem Ipsum Data",
  //   description: "Temperature data and heat flow across materials.",
  // },
  // {
  //   id: 6,
  //   icon: "/images/icon/light.jpeg",
  //   title: "Light",
  //   size: "1.2GB",
  //   downloads: 11234,
  //   category: "Optical Science",
  //   description: "Data on light intensity, reflection, and spectrum.",
  // },
];
export default featuresData;
