const featuresData = [
  {
    id: 1,
    icon: '/images/icon/Boiling.png',
    title: 'Condensation',
    size: '1.0MB',
    downloads: 15234,
    category: 'Pool boiling',
    description: 'These tests were run in two different heat loading conditions including steady state and transient ramp-up heat load.',
  },
  {
    id: 2,
    icon: '/images/icon/BubbleID.png',
    title: 'Bubble ID',
    size: '0.7MB',
    downloads: 12345,
    category: 'Heat Transfer',
    description: 'The datasets were collected from different nanostructured surfaces subjected to pool boiling experiments. These surfaces include polished copper, polished microchannel, and copper farms electrodeposited at different pHs, which are: pH 0, pH 10, ph 12.',
  },
  {
    id: 3,
    icon: '/images/icon/condensation.jpeg',
    title: 'Immersion Cooling',
    size: '0.7MB',
    downloads: 9876,
    category: 'Acoustic',
    description: 'Infrared video recordings (FLIR) of two-phase immersion cooling of a medium-voltage MOSFET, varying working fluids (HFE 7100, water) and fan duty cycles.',
  },
  // {
  //   id: 4,
  //   icon: "/images/icon/material.jpeg",
  //   title: "Material",
  //   size: "4.0GB",
  //   downloads: 54321,
  //   category: "Materials Science",
  //   description: "Properties of metals, polymers, and composites.",
  // },
  // {
  //   id: 5,
  //   icon: "/images/icon/thermal.jpeg",
  //   title: "Thermal",
  //   size: "5.0GB",
  //   downloads: 25000,
  //   category: "Lorem Ipsum Data",
  //   description: "Temperature data and heat flow across materials.",
  // },
  // {
  //   id: 6,
  //   icon: "/images/icon/light.jpeg",
  //   title: "Light",
  //   size: "1.2GB",
  //   downloads: 11234,
  //   category: "Optical Science",
  //   description: "Data on light intensity, reflection, and spectrum.",
  // },
];
export default featuresData;
